# Generated by Django 3.2.6 on 2021-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='성명')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('M', 'Medium')], max_length=10, null='True', verbose_name='사이즈')),
                ('receive', models.CharField(max_length=10, verbose_name='수령방법')),
                ('address', models.CharField(blank='True', max_length=50, null='True', verbose_name='주소')),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('beige', 'Beige')], max_length=20, null='True', verbose_name='색상')),
                ('req', models.TextField(blank='True', null='True', verbose_name='요청사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청날짜')),
            ],
            options={
                'verbose_name': '신청',
                'verbose_name_plural': '신청',
                'db_table': 'apply',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('quantity', models.IntegerField(verbose_name='모집인원')),
                ('due_date', models.DateTimeField(verbose_name='모집기간')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('tag', models.CharField(max_length=20, verbose_name='태그')),
                ('kakao_link', models.TextField(verbose_name='오픈카톡')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products_product',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/')),
                ('category', models.CharField(max_length=20, verbose_name='카테고리')),
                ('store', models.CharField(max_length=20, verbose_name='업체')),
                ('delivery', models.IntegerField(verbose_name='배송기간')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('satisfaction', models.CharField(choices=[('3', '3'), ('1', '1'), ('5', '5'), ('2', '2'), ('4', '4')], max_length=10, verbose_name='만족도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'review',
            },
        ),
    ]
