# Generated by Django 3.2.6 on 2021-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=10, null='True', verbose_name='사이즈'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('3', '3'), ('5', '5'), ('2', '2')], max_length=10, verbose_name='만족도'),
        ),
    ]
